import{i as l,S as u}from"./assets/vendor-0fc460d7.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function p(r){const s="https://pixabay.com",o="/api/",i=new URLSearchParams({key:"43954842-86e0551d49d52b31999082e7b",q:r,per_page:"21",image_type:"photo",orientation:"horizontal",safesearch:"true"}),e=`${s}${o}?${i}`;return fetch(e).then(t=>t.json())}function f(r){return r.map(({largeImageURL:s,webformatURL:o,tags:i,likes:e,views:t,comments:n,downloads:c})=>`<li class='images-list'>
            <a class='link-img' href='${s}' download onclick="return false">
            <img class='images' src='${o}' alt='${i}' width='360' height='152'/>
            <ul class='info-wrap'>
            <li class='info-container'> <p class='info-title'>Likes</p> <p class='info-value'>${e}</p> </li>
            <li class='info-container'> <p class='info-title'>Views</p> <p class='info-value'>${t}</p> </li>
            <li class='info-container'> <p class='info-title'>Comments</p> <p class='info-value'>${n}</p> </li>
            <li class='info-container'> <p class='info-title'>Downloads</p> <p class='info-value'>${c}</p> </li>
            </ul>
            </a>
            </li>`).join("")}const m=document.querySelector(".search-form");let a=document.querySelector(".images-box");const d=document.querySelector(".js-loader");m.addEventListener("submit",g);function g(r){r.preventDefault();const s=r.target.elements.query.value.trim();if(!s){l.show({message:"Please enter a search query!",backgroundColor:"#EF4040",messageColor:"#FFF",messageSize:"16px",position:"topRight",maxWidth:"432px"}),a.innerHTML="";return}d.classList.add("loader"),p(s).then(o=>{if(o.hits.length===0){l.show({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",messageColor:"#FFF",messageSize:"16px",position:"topRight",maxWidth:"432px"}),a.innerHTML="";return}else{const i=f(o.hits);a.innerHTML=i,h.refresh()}}).catch(o=>{console.log(o)}),r.target.elements.query.value=""}let h=new u(".images-box a",{captionDelay:250,captionsData:"alt",captionClass:"text-center"});
//# sourceMappingURL=commonHelpers.js.map
